;;; blue-dark-theme.el --- blue/minimalistic palette theme -*- lexical-binding: t; -*-
(deftheme blue-dark "dark theme by george")

(let ((black         "#111111")
      (dark-grey     "#171717")
      (grey-49       "#7d7d7d")
      (grey-50       "#7f7f7f")
      (off-white     "#efefef")
      (azure-light   "#e0eeee")
      (azure-grey    "#838b8b")
      (pale-turq     "#668b8b")
      (blue-steel    "#4682b4")
      (blue-deep-sky "#00688b")
      (blue-bright   "#00b2ee")
      (blue-cadet    "#8ee5ee")
      (blue-sky      "#6ca6cd")
      (blue-dodger   "#104e8b")
      (blue-pure     "#0000ee")
      (blue-light    "#add8e6")
      (steel-light   "#b0c4de")
      (slate-grey    "#778899")
      (slate-blue    "#9fb6cd")
      (cyan-dark     "#008b8b")
      (khaki         "#eee685")
      (red           "#cd0000"))
  (custom-theme-set-faces
   'blue-dark
   `(default                     ((t (:foreground ,azure-light :background ,black))))
   `(region                      ((t (:foreground ,black :background ,slate-grey))))
   `(cursor                      ((t (:foreground ,azure-light :background ,grey-50))))
   `(show-paren-match            ((t (:background ,blue-deep-sky :box (:line-width 1 :color ,azure-light :style nil)))))
   `(minibuffer-prompt           ((t (:foreground ,blue-sky))))
   `(highlight                   ((t (:inherit default :background ,blue-deep-sky))))
   `(success                     ((t (:foreground ,azure-light :weight bold))))
   `(warning                     ((t (:foreground ,khaki :weight bold))))
   `(error                       ((t (:foreground ,red :weight bold))))
   `(fringe                      ((t (:background ,black :foreground ,grey-50))))
   `(line-number                 ((t (:foreground ,steel-light))))
   `(line-number-current-line    ((t (:foreground ,blue-cadet :weight bold))))
   `(isearch                     ((t (:foreground ,azure-light :background ,blue-pure :box (:line-width 1 :color ,azure-light :style nil)))))
   `(dired-broken-symlink        ((t (:background ,khaki :foreground ,black :weight bold :slant italic))))
   `(link                        ((t (:foreground ,blue-dodger :underline t))))
   `(mode-line                   ((t (:foreground ,azure-light :background ,blue-dodger
                                       :box (:line-width 1 :color ,slate-grey :style nil)))))
   `(mode-line-active            ((t (:inherit mode-line))))
   `(mode-line-inactive          ((t (:background ,grey-49 :box (:line-width 1 :color ,grey-49 :style nil)))))
   `(font-lock-keyword-face       ((t (:foreground ,blue-steel))))
   `(font-lock-variable-name-face ((t (:foreground ,blue-deep-sky))))
   `(font-lock-string-face        ((t (:foreground ,pale-turq))))
   `(font-lock-built-in-face      ((t (:foreground ,off-white))))
   `(font-lock-type-face          ((t (:foreground ,blue-bright))))
   `(font-lock-warning-face       ((t (:inherit warning))))
   `(font-lock-constant-face      ((t (:foreground ,steel-light))))
   `(font-lock-doc-markup-face    ((t (:foreground ,off-white))))
   `(font-lock-preprocessor-face  ((t (:foreground ,off-white))))
   `(font-lock-function-name-face ((t (:foreground ,blue-cadet :weight bold))))
   `(font-lock-comment-face       ((t (:foreground ,azure-grey :slant italic))))))
(provide-theme 'blue-dark)
