# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token dark colors.

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#c67777'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[alias]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[function]='fg=#d97757'
FAST_HIGHLIGHT_STYLES[command]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#938e87'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#938e87,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#938e87'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#c67777,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#c67777,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#c67777,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[assign]='fg=#e8e4dc'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[comment]='fg=#938e87,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#d4cfc6'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#d4cfc6'
FAST_HIGHLIGHT_STYLES[variable]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#e8e4dc'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#938e87'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#c67777'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#7da47a'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#6ba8a8'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#c4956a'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#7b9ebd'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#c67777'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#7da47a'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#585855'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;123;158;189:ln=38;2;166;139;191:or=38;2;198;119;119:mi=9;38;2;198;119;119:so=38;2;125;164;122:pi=38;2;196;168;85:ex=38;2;217;119;87:bd=38;2;107;168;168:cd=38;2;107;168;168:su=1;38;2;198;119;119:sg=1;38;2;196;168;85:tw=1;38;2;125;164;122:ow=4;38;2;123;158;189:st=1;38;2;123;158;189'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;58;55;38;2;232;228;220"
zstyle ':completion:*:descriptions' format '%F{#938e87}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#938e87}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#c67777}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#e8e4dc,bg:#262624,hl:#d97757' \
  '--color=fg+:#e8e4dc,bg+:#3a3a37,hl+:#d97757' \
  '--color=border:#5a5955,header:#7b9ebd,gutter:#262624' \
  '--color=spinner:#c4956a,info:#938e87' \
  '--color=pointer:#d97757,marker:#7da47a,prompt:#d97757'
zstyle ':fzf-tab:*' default-color $'\033[38;2;232;228;220m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;123;158;189m' $'\033[38;2;125;164;122m' $'\033[38;2;196;149;106m' $'\033[38;2;166;139;191m' $'\033[38;2;107;168;168m' $'\033[38;2;217;119;87m' $'\033[38;2;196;168;85m' $'\033[38;2;198;119;119m'

# Prompt helpers
export TOKEN_FG='#e8e4dc'
export TOKEN_BG='#262624'
export TOKEN_ACCENT='#d97757'
export TOKEN_ACCENT2='#c4956a'
export TOKEN_BLUE='#7b9ebd'
export TOKEN_GREEN='#7da47a'
export TOKEN_RED='#c67777'
export TOKEN_YELLOW='#c4a855'
export TOKEN_PURPLE='#a68bbf'
export TOKEN_CYAN='#6ba8a8'
export TOKEN_MUTED='#938e87'
